import uuid
from typing import Optional, Protocol

from app.models.location import Neighborhood


class NeighborhoodAdminRepository(Protocol):
    def get_by_id(self, *, neighborhood_id: uuid.UUID) -> Optional[Neighborhood]: ...
    def get_many_by_search_names(self, *, locality_id: uuid.UUID, search_names: list[str]) -> list[Neighborhood]: ...
    def bulk_insert(self, *, neighborhoods: list[Neighborhood]) -> None: ...
    def bulk_update(self, *, neighborhoods_geom: list[dict]) -> None: ...
    def add(self, *, neighborhood: Neighborhood) -> Neighborhood: ...
