"""Database migrations for geo catalog domain

Revision ID: 9e29546801f9
Revises: 
Create Date: 2026-02-05 21:17:01.342570

"""
from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9e29546801f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS postgis')
    op.create_table('countries',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('iso_alpha2', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('iso_alpha3', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('iso_numeric', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('official_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('native_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('phone_code', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('currency_code', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('default_locale', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('default_timezone', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_supported', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso_alpha3'),
    sa.UniqueConstraint('iso_numeric')
    )
    op.create_index(op.f('ix_countries_iso_alpha2'), 'countries', ['iso_alpha2'], unique=True)
    op.create_table('admin_divisions',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('iso_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('type_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'code', name='uq_admin_div_country_code')
    )
    op.create_index('ix_admin_div_iso_code', 'admin_divisions', ['iso_code'], unique=True, postgresql_where='iso_code IS NOT NULL')
    op.create_index(op.f('ix_admin_divisions_code'), 'admin_divisions', ['code'], unique=False)
    op.create_index(op.f('ix_admin_divisions_country_id'), 'admin_divisions', ['country_id'], unique=False)
    op.create_table('localities',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('admin_division_id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('local_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('search_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('locality_type', sa.Enum('city', 'town', 'village', name='localitytype'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_capital', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['admin_division_id'], ['admin_divisions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'code', name='uq_locality_country_code')
    )
    op.create_index(op.f('ix_localities_admin_division_id'), 'localities', ['admin_division_id'], unique=False)
    op.create_index(op.f('ix_localities_code'), 'localities', ['code'], unique=False)
    op.create_index(op.f('ix_localities_country_id'), 'localities', ['country_id'], unique=False)
    op.create_index(op.f('ix_localities_search_name'), 'localities', ['search_name'], unique=False)
    op.create_index('ix_locality_coords', 'localities', ['latitude', 'longitude'], unique=False)
    op.create_table('neighborhoods',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('locality_id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('search_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['locality_id'], ['localities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('locality_id', 'code', name='uq_neighborhood_locality_code')
    )
    op.create_index('ix_neighborhood_geom', 'neighborhoods', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_neighborhoods_code'), 'neighborhoods', ['code'], unique=False)
    op.create_index(op.f('ix_neighborhoods_locality_id'), 'neighborhoods', ['locality_id'], unique=False)
    op.create_index(op.f('ix_neighborhoods_postal_code'), 'neighborhoods', ['postal_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_neighborhoods_postal_code'), table_name='neighborhoods')
    op.drop_index(op.f('ix_neighborhoods_locality_id'), table_name='neighborhoods')
    op.drop_index(op.f('ix_neighborhoods_code'), table_name='neighborhoods')
    op.drop_index('ix_neighborhood_geom', table_name='neighborhoods', postgresql_using='gist')
    op.drop_table('neighborhoods')
    op.drop_index('ix_locality_coords', table_name='localities')
    op.drop_index(op.f('ix_localities_search_name'), table_name='localities')
    op.drop_index(op.f('ix_localities_country_id'), table_name='localities')
    op.drop_index(op.f('ix_localities_code'), table_name='localities')
    op.drop_index(op.f('ix_localities_admin_division_id'), table_name='localities')
    op.drop_table('localities')
    op.drop_index(op.f('ix_admin_divisions_country_id'), table_name='admin_divisions')
    op.drop_index(op.f('ix_admin_divisions_code'), table_name='admin_divisions')
    op.drop_index('ix_admin_div_iso_code', table_name='admin_divisions', postgresql_where='iso_code IS NOT NULL')
    op.drop_table('admin_divisions')
    op.drop_index(op.f('ix_countries_iso_alpha2'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
