"""Add POI's related data

Revision ID: f2e6c93df0c6
Revises: 9e29546801f9
Create Date: 2026-02-22 23:37:10.457914

"""
from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2e6c93df0c6'
down_revision: Union[str, Sequence[str], None] = '9e29546801f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fetch_zones',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('locality_id', sa.Uuid(), nullable=False),
    sa.Column('h3_index', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('poi_count', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['locality_id'], ['localities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fetch_zones_h3_index'), 'fetch_zones', ['h3_index'], unique=True)
    op.create_index(op.f('ix_fetch_zones_is_stale'), 'fetch_zones', ['is_stale'], unique=False)
    op.create_index(op.f('ix_fetch_zones_locality_id'), 'fetch_zones', ['locality_id'], unique=False)
    op.create_table('points_of_interest',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('locality_id', sa.Uuid(), nullable=False),
    sa.Column('neighborhood_id', sa.Uuid(), nullable=True),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('source', sa.Enum('osm', 'manual', 'seed', name='poisource'), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('search_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('subcategories', postgresql.ARRAY(sa.VARCHAR(length=100)), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('h3_index', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['locality_id'], ['localities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['neighborhood_id'], ['neighborhoods.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', 'source', name='uq_poi_external_id_source')
    )
    op.create_index(
        "idx_points_of_interest_geom",
        "points_of_interest",
        ["geom"],
        postgresql_using="gist",
        if_not_exists=True,
    )
    op.create_index('ix_poi_coords', 'points_of_interest', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_poi_geom', 'points_of_interest', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_points_of_interest_category'), 'points_of_interest', ['category'], unique=False)
    op.create_index(op.f('ix_points_of_interest_external_id'), 'points_of_interest', ['external_id'], unique=False)
    op.create_index(op.f('ix_points_of_interest_h3_index'), 'points_of_interest', ['h3_index'], unique=False)
    op.create_index(op.f('ix_points_of_interest_locality_id'), 'points_of_interest', ['locality_id'], unique=False)
    op.create_index(op.f('ix_points_of_interest_neighborhood_id'), 'points_of_interest', ['neighborhood_id'], unique=False)
    op.create_index(op.f('ix_points_of_interest_search_name'), 'points_of_interest', ['search_name'], unique=False)
    # op.drop_table('spatial_ref_sys')
    op.add_column('neighborhoods', sa.Column('h3_cells', postgresql.ARRAY(sa.VARCHAR(length=16)), nullable=True))
    op.create_index('ix_neighborhood_h3_cells', 'neighborhoods', ['h3_cells'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_neighborhood_h3_cells', table_name='neighborhoods', postgresql_using='gin')
    op.drop_column('neighborhoods', 'h3_cells')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_points_of_interest_search_name'), table_name='points_of_interest')
    op.drop_index(op.f('ix_points_of_interest_neighborhood_id'), table_name='points_of_interest')
    op.drop_index(op.f('ix_points_of_interest_locality_id'), table_name='points_of_interest')
    op.drop_index(op.f('ix_points_of_interest_h3_index'), table_name='points_of_interest')
    op.drop_index(op.f('ix_points_of_interest_external_id'), table_name='points_of_interest')
    op.drop_index(op.f('ix_points_of_interest_category'), table_name='points_of_interest')
    op.drop_index('ix_poi_geom', table_name='points_of_interest', postgresql_using='gist')
    op.drop_index('ix_poi_coords', table_name='points_of_interest')
    op.drop_index('idx_points_of_interest_geom', table_name='points_of_interest', postgresql_using='gist')
    op.drop_table('points_of_interest')
    op.drop_index(op.f('ix_fetch_zones_locality_id'), table_name='fetch_zones')
    op.drop_index(op.f('ix_fetch_zones_is_stale'), table_name='fetch_zones')
    op.drop_index(op.f('ix_fetch_zones_h3_index'), table_name='fetch_zones')
    op.drop_table('fetch_zones')
    # ### end Alembic commands ###
