import uuid
from typing import Protocol

from app.models.location import PointOfInterest


class PoiRepository(Protocol):
    def get_by_external_id(self, *, external_id: str, source: str) -> PointOfInterest | None: ...

    def get_active_by_locality_id(self, *, locality_id: uuid.UUID) -> list[PointOfInterest]: ...

    def search_by_name(self, *, search_name: str, locality_id: uuid.UUID) -> list[PointOfInterest]: ...

    def get_by_h3_index(self, *, h3_index: str) -> list[PointOfInterest]: ...

    def get_by_h3_cells(self, *, h3_cells: list[str]) -> list[PointOfInterest]: ...

    def add(self, *, poi: PointOfInterest) -> None: ...

    def add_many(self, *, pois: list[PointOfInterest]) -> None: ...
