services:
  develop:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    working_dir: /workspace
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
      - "5173:5173"
      - "8080:8080"
    command: sleep infinity
    env_file:
      - .env
    networks:
      - dev-net

  users-ms-db:
    image: postgres:17
    environment:
      POSTGRES_DB: identity_service_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - users-postgres-data:/var/lib/postgresql/data
    networks:
      - dev-net
  
  catalog-ms-db:
    image: postgis/postgis:17-master
    environment:
      POSTGRES_DB: catalog_service_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - catalog-postgres-data:/var/lib/postgresql/data
    networks:
      - dev-net
  
  properties-ms-db:
    image: postgis/postgis:17-master
    environment:
      POSTGRES_DB: properties-ms-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - properties-postgres-data:/var/lib/postgresql/data
    networks:
      - dev-net
  
  analytics-ms-db:
    image: postgres:17
    environment:
      POSTGRES_DB: analytics-ms-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - analytics-postgres-data:/var/lib/postgresql/data
    networks:
      - dev-net

  keycloak-db:
    image: postgres:17
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak-postgres-data:/var/lib/postgresql/data
    networks:
      - dev-net

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.7
    depends_on:
      - keycloak-db
    command: ["start-dev", "--import-realm"]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_PROXY: edge
      
    ports:
      - "8180:8080"
    volumes:
      - ./infra/keycloak/realm.template.json:/opt/keycloak/data/import/realm.json:ro
    networks:
      - dev-net
  
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - dev-net
  
  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - '5540:5540'
    volumes:
      - redisinsight_data:/db
    networks:
      - dev-net
    environment:
      REDISINSIGHT_HOST: redis
    depends_on:
      - redis
  
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKETS: mi-casa-en-minutos
    command: server --console-address ":9001" /data
    networks:
      - dev-net
  
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.12.0-full
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow
    environment:
      TZ: UTC
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --default-artifact-root s3://mlflow-artifacts/
      --allowed-hosts "*"
    networks:
      - dev-net
  
  kafka-broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - 9092:9092
    environment:
      TZ: America/Bogota
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    networks:
      - dev-net

  topic-init:
    image: apache/kafka:latest
    depends_on:
      - kafka-broker
    entrypoint: [ 
      "sh", "-c",
      "sleep 10 && \
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server broker:29092 --create --if-not-exists --topic listing-created --partitions 1 --replication-factor 1 && \
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server broker:29092 --create --if-not-exists --topic price-predicted --partitions 1 --replication-factor 1 && \
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server broker:29092 --create --if-not-exists --topic listing-created-dlq --partitions 1 --replication-factor 1"
    ]
    networks:
      - dev-net
  
  router:
    image: openrouteservice/openrouteservice:nightly
    ports:
    - "8082:8082"
    environment:
      JAVA_OPTS: "-Xmx6g -Xms1g"
    volumes:
      - ./data/ml/AVM/data/bogota-260510.osm.pbf:/home/ors/files/osm_bogota.pbf
      - ./infra/ors/graphs:/home/ors/graphs
      - ./infra/ors/config:/home/ors/config
    networks:
      - dev-net

volumes:
  redis_data:
  redisinsight_data:
  users-postgres-data:
  catalog-postgres-data:
  properties-postgres-data:
  analytics-postgres-data:
  keycloak-postgres-data:
  minio_data:
  mlflow_data:

networks:
  dev-net:
