import uuid
from typing import Protocol

from app.models.account import Account

class AccountRepository(Protocol):
    async def create_account(self, *, account: Account) -> Account: ...
    async def get_by_id(self, *, account_id: uuid.UUID) -> Account: ...
    async def get_by_email(self, *, email: str) -> Account | None: ...