import uuid
from typing import Protocol


class IdentityProvider(Protocol):
    async def create_account(self, *, email: str, password: str) -> uuid.UUID: ...
    async def delete_account(self, account_id: uuid.UUID) -> None: ...
    async def reset_password(self, *, account_id: uuid.UUID, new_password: str) -> None: ...