"""add inserted count to bulk jobs

Revision ID: 80b6b1738d1d
Revises: f9b1c0d82f43
Create Date: 2026-07-28 00:37:12.245935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80b6b1738d1d'
down_revision: Union[str, Sequence[str], None] = 'f9b1c0d82f43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default is required, not cosmetic: adding a NOT NULL column to a
    # table that already has rows fails without one. It stays on the column so
    # any future insert that omits the field gets 0 rather than erroring.
    op.add_column(
        'bulk_jobs',
        sa.Column('inserted', sa.Integer(), nullable=False, server_default=sa.text('0')),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bulk_jobs', 'inserted')
    # ### end Alembic commands ###
