"""Refactor users ms db

Revision ID: 0304ccc99cab
Revises: 
Create Date: 2026-01-03 19:53:24.240647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0304ccc99cab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('account_type', sa.Enum('person', 'organization', name='accounttype'), nullable=False),
    sa.Column('onboarding_step', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index(op.f('ix_accounts_account_id'), 'accounts', ['account_id'], unique=False)
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    op.create_table('country',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('iso2', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('iso3', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso2'),
    sa.UniqueConstraint('iso3'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_country_id'), 'country', ['id'], unique=False)
    op.create_table('kc_compensation_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_type', sa.Enum('delete_kc_user', name='kctasktype'), nullable=False),
    sa.Column('kc_user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'done', 'failed', name='kctaskstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kc_compensation_tasks_email'), 'kc_compensation_tasks', ['email'], unique=False)
    op.create_index(op.f('ix_kc_compensation_tasks_id'), 'kc_compensation_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_kc_compensation_tasks_kc_user_id'), 'kc_compensation_tasks', ['kc_user_id'], unique=False)
    op.create_index(op.f('ix_kc_compensation_tasks_next_retry_at'), 'kc_compensation_tasks', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_kc_compensation_tasks_status'), 'kc_compensation_tasks', ['status'], unique=False)
    op.create_table('city',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'code', name='uq_city_country_id_code')
    )
    op.create_index(op.f('ix_city_country_id'), 'city', ['country_id'], unique=False)
    op.create_index(op.f('ix_city_id'), 'city', ['id'], unique=False)
    op.create_table('company_profile',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('intent', sa.Enum('buyer', 'seller', 'renter', 'explorer', name='userintent'), nullable=True),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('profile_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('user_consents',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('terms', sa.Boolean(), nullable=False),
    sa.Column('marketing', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('user_profile',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('intent', sa.Enum('buyer', 'seller', 'renter', 'explorer', name='userintent'), nullable=True),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('profile_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('neighborhood',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'name', name='uq_neighborhood_city_id_name')
    )
    op.create_index(op.f('ix_neighborhood_city_id'), 'neighborhood', ['city_id'], unique=False)
    op.create_index(op.f('ix_neighborhood_id'), 'neighborhood', ['id'], unique=False)
    op.create_table('user_interest',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'city_id', name='uq_user_interest_user_city')
    )
    op.create_index(op.f('ix_user_interest_account_id'), 'user_interest', ['account_id'], unique=False)
    op.create_index(op.f('ix_user_interest_city_id'), 'user_interest', ['city_id'], unique=False)
    op.create_index(op.f('ix_user_interest_id'), 'user_interest', ['id'], unique=False)
    op.create_table('user_neighborhood_interest',
    sa.Column('user_interest_id', sa.Uuid(), nullable=False),
    sa.Column('neighborhood_id', sa.Uuid(), nullable=False),
    sa.Column('interest_rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('interest_rank BETWEEN 1 AND 5', name='ck_interest_rank_range'),
    sa.ForeignKeyConstraint(['neighborhood_id'], ['neighborhood.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_interest_id'], ['user_interest.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_interest_id', 'neighborhood_id'),
    sa.UniqueConstraint('user_interest_id', 'interest_rank', name='uq_user_interest_rank'),
    sa.UniqueConstraint('user_interest_id', 'neighborhood_id', name='uq_user_interest_neighborhood')
    )
    op.create_index('ix_interest_rank', 'user_neighborhood_interest', ['user_interest_id', 'interest_rank'], unique=False)
    op.create_table('user_property_type_interest',
    sa.Column('user_interest_id', sa.Uuid(), nullable=False),
    sa.Column('property_type', sa.Enum('house', 'apartment', name='propertytype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_interest_id'], ['user_interest.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_interest_id', 'property_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_property_type_interest')
    op.drop_index('ix_interest_rank', table_name='user_neighborhood_interest')
    op.drop_table('user_neighborhood_interest')
    op.drop_index(op.f('ix_user_interest_id'), table_name='user_interest')
    op.drop_index(op.f('ix_user_interest_city_id'), table_name='user_interest')
    op.drop_index(op.f('ix_user_interest_account_id'), table_name='user_interest')
    op.drop_table('user_interest')
    op.drop_index(op.f('ix_neighborhood_id'), table_name='neighborhood')
    op.drop_index(op.f('ix_neighborhood_city_id'), table_name='neighborhood')
    op.drop_table('neighborhood')
    op.drop_table('user_profile')
    op.drop_table('user_consents')
    op.drop_table('company_profile')
    op.drop_index(op.f('ix_city_id'), table_name='city')
    op.drop_index(op.f('ix_city_country_id'), table_name='city')
    op.drop_table('city')
    op.drop_index(op.f('ix_kc_compensation_tasks_status'), table_name='kc_compensation_tasks')
    op.drop_index(op.f('ix_kc_compensation_tasks_next_retry_at'), table_name='kc_compensation_tasks')
    op.drop_index(op.f('ix_kc_compensation_tasks_kc_user_id'), table_name='kc_compensation_tasks')
    op.drop_index(op.f('ix_kc_compensation_tasks_id'), table_name='kc_compensation_tasks')
    op.drop_index(op.f('ix_kc_compensation_tasks_email'), table_name='kc_compensation_tasks')
    op.drop_table('kc_compensation_tasks')
    op.drop_index(op.f('ix_country_id'), table_name='country')
    op.drop_table('country')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
