"""Add new type for onboarding process

Revision ID: 207cdac5e649
Revises: b05e1bc971e0
Create Date: 2026-03-16 19:11:48.848986

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '207cdac5e649'
down_revision: Union[str, Sequence[str], None] = 'b05e1bc971e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add missing property_type value to onboardingstep enum
    op.execute("ALTER TYPE onboardingstep ADD VALUE IF NOT EXISTS 'property_type' BEFORE 'done'")

    # Drop FK constraints first before dropping referenced tables
    op.drop_constraint('user_interest_city_id_fkey', 'user_interest', type_='foreignkey')
    op.drop_constraint('user_neighborhood_interest_neighborhood_id_fkey', 'user_neighborhood_interest', type_='foreignkey')
    # Now safe to drop tables in dependency order
    op.drop_index(op.f('ix_neighborhood_city_id'), table_name='neighborhood')
    op.drop_index(op.f('ix_neighborhood_id'), table_name='neighborhood')
    op.drop_table('neighborhood')
    op.drop_index(op.f('ix_city_country_id'), table_name='city')
    op.drop_index(op.f('ix_city_id'), table_name='city')
    op.drop_table('city')
    op.drop_index(op.f('ix_country_id'), table_name='country')
    op.drop_table('country')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('user_neighborhood_interest_neighborhood_id_fkey'), 'user_neighborhood_interest', 'neighborhood', ['neighborhood_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('user_interest_city_id_fkey'), 'user_interest', 'city', ['city_id'], ['id'])
    op.create_table('country',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('iso2', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('iso3', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='country_pkey'),
    sa.UniqueConstraint('iso2', name='country_iso2_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('iso3', name='country_iso3_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('name', name='country_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_country_id'), 'country', ['id'], unique=False)
    op.create_table('neighborhood',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('city_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f('neighborhood_city_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('neighborhood_pkey')),
    sa.UniqueConstraint('city_id', 'name', name=op.f('uq_neighborhood_city_id_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_neighborhood_id'), 'neighborhood', ['id'], unique=False)
    op.create_index(op.f('ix_neighborhood_city_id'), 'neighborhood', ['city_id'], unique=False)
    op.create_table('city',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('country_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('state_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('timezone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name=op.f('city_country_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('city_pkey')),
    sa.UniqueConstraint('country_id', 'code', name=op.f('uq_city_country_id_code'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_city_id'), 'city', ['id'], unique=False)
    op.create_index(op.f('ix_city_country_id'), 'city', ['country_id'], unique=False)
    # ### end Alembic commands ###
