"""Add audit fields in account

Revision ID: 45b16114b3c6
Revises: 58398520fda2
Create Date: 2026-01-21 19:17:03.685760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '45b16114b3c6'
down_revision: Union[str, Sequence[str], None] = '58398520fda2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE TYPE accountactionactor AS ENUM (
            'user',
            'admin',
            'system'
        )
        """
    )
    op.execute(
        """
        CREATE TYPE accountdeactivationreason AS ENUM (
            'user_request',
            'policy_violation',
            'fraud',
            'other'
        )
        """
    )
    op.add_column('accounts', sa.Column('deactivated_by', sa.Enum('user', 'admin', 'system', name='accountactionactor'), nullable=True))
    op.add_column('accounts', sa.Column('deactivation_reason', sa.Enum('user_request', 'admin_ban', 'admin_suspend', 'terms_violation', 'fraud_suspected', 'system_inactive', 'system_cleanup', name='accountdeactivationreason'), nullable=True))
    op.add_column('accounts', sa.Column('deactivation_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('accounts', sa.Column('reactivated_at', sa.DateTime(), nullable=True))
    op.add_column('accounts', sa.Column('reactivated_by', sa.Enum('user', 'admin', 'system', name='accountactionactor'), nullable=True))
    op.create_unique_constraint('uq_user_interest_neighborhood', 'user_neighborhood_interest', ['user_interest_id', 'neighborhood_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_interest_neighborhood', 'user_neighborhood_interest', type_='unique')
    op.drop_column('accounts', 'reactivated_by')
    op.drop_column('accounts', 'reactivated_at')
    op.drop_column('accounts', 'deactivation_note')
    op.drop_column('accounts', 'deactivation_reason')
    op.drop_column("accounts", "deactivated_by")
    op.execute("DROP TYPE accountactionactor")
    op.execute("DROP TYPE accountdeactivationreason")
    # ### end Alembic commands ###
