"""Add photo key in profile models

Revision ID: 58398520fda2
Revises: 0304ccc99cab
Create Date: 2026-01-08 19:00:01.148368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58398520fda2'
down_revision: Union[str, Sequence[str], None] = '0304ccc99cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userintent RENAME TO accountintent")
    op.add_column('company_profile', sa.Column('photo_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('company_profile', 'intent',
               existing_type=postgresql.ENUM('buyer', 'seller', 'renter', 'explorer', name='userintent'),
               type_=sa.Enum('buyer', 'seller', 'renter', 'explorer', name='accountintent'),
               existing_nullable=True)
    op.execute(
        "ALTER TABLE user_neighborhood_interest "
        "RENAME CONSTRAINT uq_user_interest_neighborhood TO uq_user_profile_neighborhood_v2"
    )
    op.add_column('user_profile', sa.Column('photo_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('user_profile', 'intent',
               existing_type=postgresql.ENUM('buyer', 'seller', 'renter', 'explorer', name='userintent'),
               type_=sa.Enum('buyer', 'seller', 'renter', 'explorer', name='accountintent'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'intent',
               existing_type=sa.Enum('buyer', 'seller', 'renter', 'explorer', name='accountintent'),
               type_=postgresql.ENUM('buyer', 'seller', 'renter', 'explorer', name='userintent'),
               existing_nullable=True)
    op.drop_column('user_profile', 'photo_key')
    op.drop_constraint('uq_user_interest_neighborhood', 'user_neighborhood_interest', type_='unique')
    op.alter_column('company_profile', 'intent',
               existing_type=sa.Enum('buyer', 'seller', 'renter', 'explorer', name='accountintent'),
               type_=postgresql.ENUM('buyer', 'seller', 'renter', 'explorer', name='userintent'),
               existing_nullable=True)
    op.drop_column('company_profile', 'photo_key')
    # ### end Alembic commands ###
