"""Add onboarding completions table

Revision ID: 971c772670f6
Revises: 207cdac5e649
Create Date: 2026-03-16 19:19:21.329674

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM as PgEnum

# revision identifiers, used by Alembic.
revision: str = '971c772670f6'
down_revision: Union[str, Sequence[str], None] = '207cdac5e649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_completions',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('key', PgEnum('intent', 'city', 'neighborhood', 'property_type', 'done', name='onboardingstep', create_type=False), nullable=False),
    sa.Column('completed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', 'key')
    )
    op.create_index('ix_onboarding_account_id', 'onboarding_completions', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_onboarding_account_id', table_name='onboarding_completions')
    op.drop_table('onboarding_completions')
    # ### end Alembic commands ###
