apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: infra
    app.kubernetes.io/part-of: platform
    env: dev
spec:
  selector:
    app.kubernetes.io/name: keycloak
    env: dev
  ports:
    - name: http
      port: 8080
      targetPort: http