apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.app.name }}-ms-config"
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  {{- include "microservice.configData" . | nindent 2 }}