apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app.name }}"
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    {{- include "microservice.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}