from typing import Any, Protocol


class CachePort(Protocol):
    async def get(self, *, key: str) -> str | None: ...
    async def mget(self, *, keys: list[str]) -> list[str | None]: ...
    async def getdel(self, *, key: str) -> str | None: ...
    async def set(self, *, key: str, value: str, ttl: int | None = None) -> None: ...
    async def delete(self, *, key: str | list[str]) -> None: ...
    async def get_json(self, *, key: str) -> dict | list | None: ...
    async def mget_json(self, *, keys: list[str]) -> list[Any | None]: ...
    async def getdel_json(self, *, key: str) -> dict | list | None: ...
    async def set_json(self, *, key: str, value: dict | list, ttl: int | None = None) -> None: ...
    async def set_nx(self, *, key: str, value: str, ttl: int | None = None) -> bool: ...
    async def mset(self, *, data: dict[str, Any]) -> None: ...
    async def mset_json(self, *, data: dict[str, Any], ttl: int | None = None) -> None: ...
