from typing import Protocol, AsyncIterator

class StoragePort(Protocol):
    async def generate_presigned_put_url(self, *, bucket: str, key: str, ttl: int) -> str: ...
    async def generate_presigned_put_urls(self, *, bucket: str, keys: list[str], ttl: int) -> list[str]: ...
    async def chunk_file(self, *, bucket: str, key: str) -> AsyncIterator[bytes]: ...