from typing import Any, Protocol

class CachePort(Protocol):
    async def get(self, *, key: str) -> str | None: ...
    async def set(self, *, key: str, value: str, ttl: int | None = None) -> None: ...
    async def delete(self, *, key: str) -> None: ...
    async def get_json(self, *, key: str) -> dict[str, Any] | None: ...
    async def set_json(self, *, key: str, value: dict[str, Any], ttl: int | None = None) -> None: ...
