import uuid
from typing import Protocol

from app.models.property import Property


class PropertyRepository(Protocol):
    def add(self, *, property: Property) -> None: ...
    def get_user_properties(self, *, user_id: uuid.UUID) -> list[Property]: ...
    def get_public_user_properties(self, *, user_id: uuid.UUID) -> list[Property]: ...
    def get_by_id(self, *, property_id: uuid.UUID) -> Property | None: ...
    def get_by_id_for_update(self, *, property_id: uuid.UUID) -> Property | None: ...
