import uuid
from datetime import datetime
from typing import Optional, Protocol

from app.models.property import PropertyImage, PropertyImageUploadBatch


class PropertyImageRepository(Protocol):
    def add(self, *, image: PropertyImage) -> None: ...
    def get_active_ids(self, *, property_id: uuid.UUID) -> list[uuid.UUID]: ...
    def get_images(self, *, property_id: uuid.UUID, image_ids: list[uuid.UUID] | None = None) -> list[PropertyImage]: ...
    def add_batch(self, *, batch: PropertyImageUploadBatch) -> None: ...
    def get_batch(self, *, batch_id: uuid.UUID) -> Optional[PropertyImageUploadBatch]: ...
    def get_open_batches(self, *, property_id: uuid.UUID, now: datetime, exclude_ids: list[uuid.UUID] | None = None) -> list[PropertyImageUploadBatch]: ...
