import uuid
from typing import Protocol

from app.models.property import PromotedListing


class PromotionRepository(Protocol):
    def add(self, *, promotion: PromotedListing) -> None: ...
    def flush(self) -> None: ...
    def get_active_by_property_id(self, *, property_id: uuid.UUID) -> PromotedListing | None: ...
    def get_all(self) -> list[PromotedListing]: ...
    def get_all_by_property_id(self, *, property_id: uuid.UUID) -> list[PromotedListing]: ...
    def delete(self, *, promotion: PromotedListing) -> None: ...