import uuid
from typing import Protocol

from app.models.promotion import PromotedListing


class PromotionRepository(Protocol):
    def add(self, *, promotion: PromotedListing) -> None: ...
    def flush(self) -> None: ...
    def get_active_by_property_id(self, *, property_id: uuid.UUID) -> PromotedListing | None: ...
    def get_all(self, *, offset: int, limit: int) -> list[PromotedListing]: ...
    def count_all(self) -> int: ...
    def delete(self, *, promotion: PromotedListing) -> None: ...